# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :updateVersionings do |options|
    increment_build_number(
      build_number: options[:run_number].to_i
    )
  
    # increment_version_number_in_xcodeproj(
    #   version_number: "#{options[:current_version]}" # Set a specific version number
    # )
  end

  lane :beta do
    setup_ci
    clear_derived_data
   api_key1 = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
    )
    # add actions here: https://docs.fastlane.tools/actions
    match(api_key:api_key1,git_branch: "master", type: "appstore", app_identifier: ["com.yangang.rtmppush"])


    run_number = ENV["SH_run_number"]
    puts "------====== ==== ffffff"
    version = get_version_number(
      target: "TestUpload",
      configuration: "Release"
    )
    buildNumber = get_build_number.to_i
    test_bumber = run_number.to_i
    buildNumber = test_bumber + buildNumber
    puts "------====== ====1 test_bumber #{test_bumber} buildNumber--#{buildNumber} -- #{version}"

    updateVersionings(
       run_number: buildNumber,
       current_version: version
    )
    # build_app(workspace: "MusicDemo.xcworkspace", scheme: "MusicDemo", export_method: "app-store")
    build_app(
      export_method: "app-store",
      scheme: "TestUpload",
      project: "TestUpload.xcodeproj")
    upload_to_testflight(api_key: api_key1,skip_submission: true)
  end
end
